In [1]:
import pickle
import numpy as np

In [2]:
DATA_FILE_PATH = 'smokin2mp4.pkl'
with open(DATA_FILE_PATH, 'rb') as file:
    data = pickle.load(file)

## data format: list of dicts for the analyzed frames of the following fields:
{'frame_id', 'body_parts', 'all_peaks', 'subset', 'candiate'}

In [3]:
COCO_BODY_PARTS = ['nose', 'neck',
                   'right_shoulder', ' right_elbow', 'right_wrist',
                   'left_shoulder', 'left_elbow', 'left_wrist',
                   'right_hip', 'right_knee', 'right_ankle',
                   'left_hip', 'left_knee', 'left_ankle',
                   'right_eye', 'left_eye', 'right_ear', 'left_ear', 'background'
                   ]
len(COCO_BODY_PARTS)

19

In [71]:
coco_parts_xy = [[part + '_x', part + '_y'] for part in COCO_BODY_PARTS[0:-1]]


['nose_x',
 'nose_y',
 'neck_x',
 'neck_y',
 'right_shoulder_x',
 'right_shoulder_y',
 ' right_elbow_x',
 ' right_elbow_y',
 'right_wrist_x',
 'right_wrist_y',
 'left_shoulder_x',
 'left_shoulder_y',
 'left_elbow_x',
 'left_elbow_y',
 'left_wrist_x',
 'left_wrist_y',
 'right_hip_x',
 'right_hip_y',
 'right_knee_x',
 'right_knee_y',
 'right_ankle_x',
 'right_ankle_y',
 'left_hip_x',
 'left_hip_y',
 'left_knee_x',
 'left_knee_y',
 'left_ankle_x',
 'left_ankle_y',
 'right_eye_x',
 'right_eye_y',
 'left_eye_x',
 'left_eye_y',
 'right_ear_x',
 'right_ear_y',
 'left_ear_x',
 'left_ear_y']

In [76]:
array_header = ['frame_id', 'bbox_x1', 'bbox_y1', 'bbox_x2', 'bbox_y2'] + [l.strip(' ') for p in coco_parts_xy for l in p] + ['config_score', 'no_joints', 'object_id']
print(len(array_header))
array_header

44


['frame_id',
 'bbox_x1',
 'bbox_y1',
 'bbox_x2',
 'bbox_y2',
 'nose_x',
 'nose_y',
 'neck_x',
 'neck_y',
 'right_shoulder_x',
 'right_shoulder_y',
 'right_elbow_x',
 'right_elbow_y',
 'right_wrist_x',
 'right_wrist_y',
 'left_shoulder_x',
 'left_shoulder_y',
 'left_elbow_x',
 'left_elbow_y',
 'left_wrist_x',
 'left_wrist_y',
 'right_hip_x',
 'right_hip_y',
 'right_knee_x',
 'right_knee_y',
 'right_ankle_x',
 'right_ankle_y',
 'left_hip_x',
 'left_hip_y',
 'left_knee_x',
 'left_knee_y',
 'left_ankle_x',
 'left_ankle_y',
 'right_eye_x',
 'right_eye_y',
 'left_eye_x',
 'left_eye_y',
 'right_ear_x',
 'right_ear_y',
 'left_ear_x',
 'left_ear_y',
 'config_score',
 'no_joints',
 'object_id']

## body parts
one example of coordiinates for every COCO body part. USELESS

In [4]:
body_parts = np.array(data[25]['body_parts'])
body_parts

array({'nose': (230, 87), 'neck': (145, 100), 'right_shoulder': (228, 97), ' right_elbow': (127, 114), 'right_wrist': (130, 129), 'left_shoulder': (157, 100), 'left_elbow': (159, 121), 'left_wrist': (145, 133), 'right_hip': (229, 134), 'right_knee': (226, 156), 'right_ankle': (223, 174), 'left_hip': (154, 134), 'left_knee': (153, 160), 'left_ankle': (151, 184), 'right_eye': (229, 84), 'left_eye': (233, 84), 'right_ear': (138, 88), 'left_ear': (241, 85)},
      dtype=object)

## all_peaks
a list of lists each corresponding to a COCO body part made of tuples of the following format of locs:
(x, y, confidence, peak_id)

In [5]:
all_peaks = np.array(data[0]['all_peaks'])
all_peaks

array([list([(234, 87, 0.9083782434463501, 0), (181, 96, 0.5591726899147034, 1)]),
       list([(169, 99, 0.765608012676239, 2), (241, 100, 0.9036915898323059, 3), (196, 118, 0.8418397307395935, 4)]),
       list([(230, 97, 0.864372193813324, 5), (163, 100, 0.8208009600639343, 6), (210, 124, 0.8031818270683289, 7)]),
       list([(227, 114, 0.7221102118492126, 8), (158, 120, 0.8832500576972961, 9), (215, 151, 0.8135343790054321, 10)]),
       list([(178, 115, 0.6068695187568665, 11), (226, 129, 0.6727707982063293, 12), (232, 157, 0.5008898377418518, 13)]),
       list([(177, 99, 0.5348705053329468, 14), (251, 103, 0.8400102257728577, 15), (182, 113, 0.7927486896514893, 16)]),
       list([(252, 124, 0.8243544101715088, 17)]),
       list([(244, 142, 0.7252730131149292, 18)]),
       list([(167, 134, 0.8585205674171448, 19), (230, 134, 0.7712255120277405, 20), (204, 167, 0.680644690990448, 21)]),
       list([(226, 155, 0.8229906558990479, 22), (167, 157, 0.8823679089546204, 23), (201, 

## subset
an array in which each row corresponds to a different "object" with the row items indicating the peak_id's in all_peaks. the column index corresponds to the COCO body part index

    # last number in each row is the total parts number of that person
    # the second last number in each row is the score of the overall configuration

In [6]:
subset = np.array(data[0]['subset'])
subset

array([[ 0.        ,  3.        ,  5.        ,  8.        , 12.        ,
        15.        , 17.        , 18.        , 20.        , 22.        ,
        25.        , 29.        , 32.        , 35.        , 37.        ,
        39.        , -1.        , 43.        , 28.89961997, 17.        ],
       [-1.        ,  4.        ,  7.        , 10.        , 13.        ,
        16.        , -1.        , -1.        , 21.        , 24.        ,
        27.        , 30.        , 33.        , 36.        , -1.        ,
        -1.        , 42.        , 44.        , 18.56997137, 13.        ],
       [ 1.        ,  2.        ,  6.        ,  9.        , 11.        ,
        14.        , -1.        , -1.        , 19.        , 23.        ,
        26.        , 28.        , 31.        , 34.        , 38.        ,
        40.        , 41.        , -1.        , 21.81312792, 15.        ]])

## Candidate
array in which each row is one of the peaks, same as each tuple in all_peaks

In [7]:
candidate = np.array(data[0]['candidate'])
candidate

array([[234.        ,  87.        ,   0.90837824,   0.        ],
       [181.        ,  96.        ,   0.55917269,   1.        ],
       [169.        ,  99.        ,   0.76560801,   2.        ],
       [241.        , 100.        ,   0.90369159,   3.        ],
       [196.        , 118.        ,   0.84183973,   4.        ],
       [230.        ,  97.        ,   0.86437219,   5.        ],
       [163.        , 100.        ,   0.82080096,   6.        ],
       [210.        , 124.        ,   0.80318183,   7.        ],
       [227.        , 114.        ,   0.72211021,   8.        ],
       [158.        , 120.        ,   0.88325006,   9.        ],
       [215.        , 151.        ,   0.81353438,  10.        ],
       [178.        , 115.        ,   0.60686952,  11.        ],
       [226.        , 129.        ,   0.6727708 ,  12.        ],
       [232.        , 157.        ,   0.50088984,  13.        ],
       [177.        ,  99.        ,   0.53487051,  14.        ],
       [251.        , 103

# Create data structure per person in video
Try to create a 3D array of coordinates and time for each person

1) parse pkl for coordinates for each body part per frame

2) match same person between frames - based on the minimum change in head location between consecutive frames

3) filter in time out bad pose estimates, based on:
    a. smoothing filter
    b. pose estimate confidence
 

## How many persons there are in the video?
Go over all frames and understand what is the average number of people.

Choose representative middle frame from which to identify persons accross frames.

In [8]:
def how_many_persons_video(data, person_thresh=0): # TODO: need to figure out person configuration score threshold
    no_persons = np.zeros(len(data))
    for i, frame_data in enumerate(data):
        subset = np.array(frame_data['subset'])
        for person in subset:
            if person[18] > person_thresh:
                no_persons[i] += 1
    return no_persons

In [9]:
# test
how_many_persons_video(data, 0)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 4., 4., 4., 3., 3., 3., 3., 3., 3., 4.,
       3., 3., 3., 3., 3., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

## frame level

In [10]:
all_peaks = np.array(data[0]['all_peaks'])
subset = np.array(data[0]['subset'])
candidate = np.array(data[0]['candidate'])
person_thresh = 0 
joint_thresh = 0

def get_person_pose_frame(person, candidate, person_thresh=0, joint_thresh=0):
    ''' extracts body positions for given person (item in the "subset" list)'''
    confidence = person[18]     # check confidence level
    if confidence < person_thresh:
        return False
    joints = person[0:18]
    joints_locs = np.zeros((18, 2))
    for i, joint in enumerate(joints):
        j = int(joint)
        if joint == -1:
            joints_locs[i, :] = [-1, -1]
        elif candidate[j, 2] < joint_thresh:
            joints_locs[i, :] = [-1, -1]
        else:
            joints_locs[i, :] = candidate[j, 0:2]
            
    return joints_locs

# check
for person in subset:
    joints_locs = get_person_pose_frame(person, candidate)

In [11]:
joints_locs[joints_locs <= 0] = np.inf
joints_locs

array([[181.,  96.],
       [169.,  99.],
       [163., 100.],
       [158., 120.],
       [178., 115.],
       [177.,  99.],
       [ inf,  inf],
       [ inf,  inf],
       [167., 134.],
       [167., 157.],
       [165., 180.],
       [177., 133.],
       [175., 155.],
       [173., 173.],
       [179.,  93.],
       [184.,  94.],
       [174.,  90.],
       [ inf,  inf]])

## Matching between persons in different frames
So run previous function on all frames, see when getting head locations, and them match them based on minimal head loc change distanvce

In [17]:
from sklearn.metrics import pairwise_distances
# get max characters in video
n_joints = 18
head_loc_idx = 1
max_no_people = max(how_many_persons_video(data))
n_frames = len(data)
joints_array = np.zeros((n_joints, 2, max_no_people, n_frames))

for i, frame_data in enumerate(data):
    subset = np.array(frame_data['subset'])

    if i == 0:
        for p, person in enumerate(subset):
            joints_locs = get_person_pose_frame(person, candidate)
            joints_array[:, :, p, i] = joints_locs
            
    else:
        for p, person in enumerate(subset):
            joints_locs = get_person_pose_frame(person, candidate)
            head_loc = joints_loc[head_loc_idx, :]
            dist_mat = pairwise_distances(head_loc, joints_array[head_loc_idx, :, :, i-1], 
                                          metric='euclidean', n_jobs=-1)
            min_idx = np.argmin(dist_mat)
            joints_array[:, :, p, i] = joints_locs
            

TypeError: 'numpy.float64' object cannot be interpreted as an integer

# create bounding box for head location per person to be used in SORT tracking algorithm

In [18]:
def get_person_pose_frame(person, candidate, person_thresh=0, joint_thresh=0):
    ''' extracts body positions for given person (item in the "subset" list) '''
    no_joints = person[19]
    config_score = person[18]     # check configuration score
    if config_score < person_thresh:
        return False
    joints = person[0:18]
    joints_locs = np.zeros((18, 2))
    for i, joint in enumerate(joints):
        j = int(joint)
        if joint == -1 or j >= len(candidate):
            joints_locs[i, :] = [-1, -1]
        elif candidate[j, 2] < joint_thresh:
            joints_locs[i, :] = [-1, -1]
        else:
            joints_locs[i, :] = candidate[j, 0:2]
            
    return joints_locs, config_score, no_joints

In [19]:
def get_bbox_from_pose(joints_locs):
    joints_locs_min = joints_locs.copy()
    joints_locs_min[joints_locs <= 0] = np.inf
    
    minx = min(joints_locs_min[:, 0])
    miny = min(joints_locs_min[:, 1])
    maxx = max(joints_locs[:, 0])
    maxy = max(joints_locs[:, 1])
    return [minx, miny, maxx, maxy]

In [50]:
def get_bbox_center(bbox):
    '''Returns the x, y coordinates of the center of a 
    bounding box of the following format [x1,y1,x2,y2] (opposite corners).
    bbox = array of bounding boxes '''
    if len(bbox.shape) == 1:
        bbox = bbox.reshape(1, -1)
    x = np.mean(bbox[:,[0, 2]], axis=1)
    y = np.mean(bbox[:,[1, 3]], axis=1)
    return np.column_stack((x, y))

In [53]:
A = np.array([1 , 2, 3, 4])
get_bbox_center(A)

array([[2., 3.]])

In [20]:
def get_all_joints(data):
    '''Function outputs an array of detected persons in each frame , 
    their joint body parts x, y locations and bounding box [x1,y1,x2,y2]'''
    joints_array = []
    for i, frame_data in enumerate(data):
        # print(f'Processing frame {i}')
        subset = np.array(frame_data['subset'])
        for person in subset:
            joints_locs, confidence, no_joints = get_person_pose_frame(person, candidate)
            bboxes = get_bbox_from_pose(joints_locs)
            joints_array.append([i] + list(bboxes) + list(joints_locs.flatten())+ [confidence, no_joints])
    return np.array(joints_array)

In [21]:
# test
joints_array = get_all_joints(data)

In [64]:
from sklearn.metrics import pairwise_distances_argmin
from sort.sort import *

#create instance of SORT
mot_tracker = Sort() 

# get detections
joints_array = get_all_joints(data)
object_ids = []
for i in range(len(data)):
    detections = joints_array[joints_array[:, 0] == i, 1:5]
    # update SORT
    # trackers is a np array where each row contains a valid bounding box and track_id (last column)
    trackers = mot_tracker.update(detections)
    
    # match detections and trackers based on bbox centers distance
    det_centers = get_bbox_center(detections)
    trk_centers = get_bbox_center(trackers[:,0:4])
    indexes = pairwise_distances_argmin(det_centers, trk_centers, axis=0, metric='euclidean')
    object_ids_frame = np.tile(-1, detections.shape[0])
    object_ids_frame[indexes] = trackers[:, -1]
    object_ids += list(object_ids_frame)
    
# concatenate object ids as new column to joints_array
object_ids = np.array(object_ids)
object_ids[object_ids >=0] = object_ids[object_ids >=0] - min(object_ids[object_ids >=0]) # reindex from 0
joints_array = np.column_stack((joints_array, object_ids))
print(joints_array)

[[  0.         224.          83.         ...  28.89961997  17.
    0.        ]
 [  0.         182.          96.         ...  18.56997137  13.
    1.        ]
 [  0.         158.          90.         ...  21.81312792  15.
    2.        ]
 ...
 [ 48.         158.          99.         ...  18.43457406  12.
    3.        ]
 [ 49.         158.          87.         ...  15.64857325  12.
    0.        ]
 [ 49.         163.          99.         ...  18.38607021  12.
    3.        ]]


In [79]:
int(joints_array[:, -1].max())

4

# Create video with joints and bounding boxes
## Canvas function from OpenPose

In [77]:
import math

import numpy as np
from scipy.ndimage.filters import gaussian_filter
import cv2

import util

In [ ]:
# read file
filepath = os.path.join(data_dir, filename)
with open(filepath, 'rb') as file:
    data = pickle.load(file)

In [85]:
def draw_boxes(input_image, frame_data, no_objects, colors):
    canvas = input_image.copy()
    colors = []
    for i, c in enumerate(colors):
        cur_canvas = canvas.copy()
        object_bbox = tuple(frame_data[frame_data[:, -1].astype(int) == i, 1:5].astype(int))
        cv2.rectangle(cur_canvas, object_bbox, color=c,
                                thickness=3)
        canvas = cv2.addWeighted(canvas, 0.4, cur_canvas, 0.6, 0)
        
    return canvas

In [83]:
def draw_joints(input_image, all_peaks, subset, candidate, resize_fac=1):
    canvas = input_image.copy()

    for i in range(18):
        for j in range(len(all_peaks[i])):
            a = all_peaks[i][j][0] * resize_fac
            b = all_peaks[i][j][1] * resize_fac
            cv2.circle(canvas, (a, b), 2, util.colors[i], thickness=-1)

    stickwidth = 4

    for i in range(17):
        for s in subset:
            index = s[np.array(util.limbSeq[i]) - 1]
            if -1 in index:
                continue
            cur_canvas = canvas.copy()
            y = candidate[index.astype(int), 0]
            x = candidate[index.astype(int), 1]
            m_x = np.mean(x)
            m_y = np.mean(y)
            length = ((x[0] - x[1]) ** 2 + (y[0] - y[1]) ** 2) ** 0.5
            angle = math.degrees(math.atan2(x[0] - x[1], y[0] - y[1]))
            polygon = cv2.ellipse2Poly((int(m_y * resize_fac), int(m_x * resize_fac)),
                                       (int(length * resize_fac / 2), stickwidth), int(angle), 0, 360, 1)
            cv2.fillConvexPoly(cur_canvas, polygon, util.colors[i])
            canvas = cv2.addWeighted(canvas, 0.4, cur_canvas, 0.6, 0)
        
    return canvas

In [82]:
def color_generator(n):
    colors = []
    for i in range(n):
        colors.append((np.random.randint(255), np.random.randint(255), np.random.randint(255)))
    return colors

In [ ]:
print('start processing...')
frame_rate_ratio = 3

# Video input
# video = videoname
video_path = 'videos/'
video_file = video_path + video

# Output location
output_path = 'videos/outputs/'
output_format = '.mp4'
video_output = output_path + video + str(start_datetime) + output_format

# Video reader
cam = cv2.VideoCapture(video_file)
input_fps = cam.get(cv2.CAP_PROP_FPS)
ret_val, orig_image = cam.read()
video_length = int(cam.get(cv2.CAP_PROP_FRAME_COUNT))
ending_frame = video_length


# Video writer
output_fps = input_fps / frame_rate_ratio
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(video_output, fourcc, output_fps, (orig_image.shape[1], orig_image.shape[0]))

# object (person) tracking
no_objects = int(array[:, -1].max()) + 1
colors = color_generator(no_objects)

i = 0  # input video frame id
j = 0  # analyzed frames id
while(cam.isOpened()) and ret_val is True and i < ending_frame:
    if i % frame_rate_ratio == 0:
    
        input_image = cv2.cvtColor(orig_image, cv2.COLOR_RGB2BGR)

        tic = time.time()

        # generate image with body parts
        body_parts, all_peaks, subset, candidate = data[j, 1:5]
        canvas = draw_joints(orig_image, all_peaks, subset, candidate)
        
        # draw bounding boxes based on data analyzed by joint_tracking.py
        frame_data = array[array[:, 0].astype(int) == i, :]
        canvas = draw_boxes(canvas, frame_data, no_objects, colors)
        print('Processing frame: ', i)
        toc = time.time()
        print('processing time is %.5f' % (toc - tic))

        out.write(canvas)
        j += 1
    ret_val, orig_image = cam.read()

    i += 1
